<?php

namespace App\Http\Controllers\Etc;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ToolsController extends Controller
{
    public function getCountryNationality($countryCode)
    {
        $countries = [
            // Africa
            'DZ' => 'Algerian',
            'AO' => 'Angolan',
            'BJ' => 'Beninese',
            'BW' => 'Botswanan',
            'BF' => 'Burkinabe',
            'BI' => 'Burundian',
            'CM' => 'Cameroonian',
            'CV' => 'Cape Verdean',
            'CF' => 'Central African',
            'TD' => 'Chadian',
            'KM' => 'Comoran',
            'CG' => 'Congolese',
            'CD' => 'Congolese',
            'CI' => 'Ivorian',
            'DJ' => 'Djiboutian',
            'EG' => 'Egyptian',
            'GQ' => 'Equatorial Guinean',
            'ER' => 'Eritrean',
            'ET' => 'Ethiopian',
            'GA' => 'Gabonese',
            'GM' => 'Gambian',
            'GH' => 'Ghanaian',
            'GN' => 'Guinean',
            'GW' => 'Guinea-Bissauan',
            'KE' => 'Kenyan',
            'LS' => 'Basotho',
            'LR' => 'Liberian',
            'LY' => 'Libyan',
            'MG' => 'Malagasy',
            'MW' => 'Malawian',
            'ML' => 'Malian',
            'MR' => 'Mauritanian',
            'MU' => 'Mauritian',
            'YT' => 'Mahoran',
            'MA' => 'Malaysian',
            'MZ' => 'Mozambican',
            'NA' => 'Namibian',
            'NE' => 'Nigerien',
            'NG' => 'Nigerian',
            'RW' => 'Rwandan',
            'RE' => 'Réunionese',
            'SH' => 'Saint Helenian',
            'SN' => 'Senegalese',
            'SC' => 'Seychellois',
            'SL' => 'Sierra Leonean',
            'SO' => 'Somali',
            'ZA' => 'South African',
            'SD' => 'Sudanese',
            'SZ' => 'Swazi',
            'ST' => 'São Toméan',
            'TZ' => 'Tanzanian',
            'TG' => 'Togolese',
            'TN' => 'Tunisian',
            'UG' => 'Ugandan',
            'EH' => 'Sahrawi',
            'ZM' => 'Zambian',
            'ZW' => 'Zimbabwean',

            // Americas
            'AI' => 'Anguillan',
            'AG' => 'Antiguan',
            'AR' => 'Argentine',
            'AW' => 'Aruban',
            'BS' => 'Bahamian',
            'BB' => 'Barbadian',
            'BZ' => 'Belizean',
            'BM' => 'Bermudian',
            'BO' => 'Bolivian',
            'BR' => 'Brazilian',
            'VG' => 'British Virgin Islander',
            'CA' => 'Canadian',
            'KY' => 'Caymanian',
            'CL' => 'Chilean',
            'CO' => 'Colombian',
            'CR' => 'Costa Rican',
            'CU' => 'Cuban',
            'DM' => 'Dominican',
            'DO' => 'Dominican',
            'EC' => 'Ecuadorian',
            'SV' => 'Salvadoran',
            'FK' => 'Falkland Islander',
            'GF' => 'French Guianese',
            'GL' => 'Greenlandic',
            'GD' => 'Grenadian',
            'GP' => 'Guadeloupean',
            'GT' => 'Guatemalan',
            'GY' => 'Guyanese',
            'HT' => 'Haitian',
            'HN' => 'Honduran',
            'JM' => 'Jamaican',
            'MQ' => 'Martinican',
            'MX' => 'Mexican',
            'MS' => 'Montserratian',
            'NI' => 'Nicaraguan',
            'PA' => 'Panamanian',
            'PY' => 'Paraguayan',
            'PE' => 'Peruvian',
            'PR' => 'Puerto Rican',
            'BL' => 'Barthélemois',
            'KN' => 'Kittitian',
            'LC' => 'Saint Lucian',
            'MF' => 'Saint-Martinoise',
            'PM' => 'Saint-Pierrais',
            'VC' => 'Vincentian',
            'SR' => 'Surinamese',
            'TT' => 'Trinidadian',
            'TC' => 'Turks and Caicos Islander',
            'VI' => 'Virgin Islander',
            'US' => 'American',
            'UY' => 'Uruguayan',
            'VE' => 'Venezuelan',

            // Asia
            'AF' => 'Afghan',
            'AM' => 'Armenian',
            'AZ' => 'Azerbaijani',
            'BH' => 'Bahraini',
            'BD' => 'Bangladeshi',
            'BT' => 'Bhutanese',
            'BN' => 'Bruneian',
            'KH' => 'Cambodian',
            'CN' => 'Chinese',
            'GE' => 'Georgian',
            'HK' => 'Hong Konger',
            'IN' => 'Indian',
            'ID' => 'Indonesian',
            'IR' => 'Iranian',
            'IQ' => 'Iraqi',
            'IL' => 'Israeli',
            'JP' => 'Japanese',
            'JO' => 'Jordanian',
            'KZ' => 'Kazakhstani',
            'KW' => 'Kuwaiti',
            'KG' => 'Kyrgyz',
            'LA' => 'Laotian',
            'LB' => 'Lebanese',
            'MO' => 'Macanese',
            'MY' => 'Moroccan',
            'MV' => 'Maldivian',
            'MN' => 'Mongolian',
            'MM' => 'Burmese',
            'NP' => 'Nepalese',
            'KP' => 'North Korean',
            'OM' => 'Omani',
            'PK' => 'Pakistani',
            'PS' => 'Palestinian',
            'PH' => 'Filipino',
            'QA' => 'Qatari',
            'SA' => 'Saudi',
            'SG' => 'Singaporean',
            'KR' => 'South Korean',
            'LK' => 'Sri Lankan',
            'SY' => 'Syrian',
            'TW' => 'Taiwanese',
            'TJ' => 'Tajikistani',
            'TH' => 'Thai',
            'TL' => 'Timorese',
            'TR' => 'Turkish',
            'TM' => 'Turkmen',
            'AE' => 'Emirati',
            'UZ' => 'Uzbekistani',
            'VN' => 'Vietnamese',
            'YE' => 'Yemeni',

            // Europe
            'AL' => 'Albanian',
            'AD' => 'Andorran',
            'AT' => 'Austrian',
            'BY' => 'Belarusian',
            'BE' => 'Belgian',
            'BA' => 'Bosnian',
            'BG' => 'Bulgarian',
            'HR' => 'Croatian',
            'CY' => 'Cypriot',
            'CZ' => 'Czech',
            'DK' => 'Danish',
            'EE' => 'Estonian',
            'FI' => 'Finnish',
            'FR' => 'French',
            'DE' => 'German',
            'GR' => 'Greek',
            'HU' => 'Hungarian',
            'IS' => 'Icelandic',
            'IE' => 'Irish',
            'IT' => 'Italian',
            'XK' => 'Kosovar',
            'LV' => 'Latvian',
            'LI' => 'Liechtensteiner',
            'LT' => 'Lithuanian',
            'LU' => 'Luxembourgish',
            'MT' => 'Maltese',
            'MD' => 'Moldovan',
            'MC' => 'Monégasque',
            'ME' => 'Montenegrin',
            'NL' => 'Dutch',
            'MK' => 'Macedonian',
            'NO' => 'Norwegian',
            'PL' => 'Polish',
            'PT' => 'Portuguese',
            'RO' => 'Romanian',
            'RU' => 'Russian',
            'SM' => 'Sammarinese',
            'RS' => 'Serbian',
            'SK' => 'Slovak',
            'SI' => 'Slovenian',
            'ES' => 'Spanish',
            'SE' => 'Swedish',
            'CH' => 'Swiss',
            'UA' => 'Ukrainian',
            'GB' => 'British',
            'VA' => 'Vatican',
        ];

        return $countries[$countryCode] ?? 'Unknown';
    }
}
